/**
 * Mock URL Scraper Service
 * Provides fallback mock data when Firecrawl is not available
 */

import { ScrapedProjectData, isUrl as isUrlCheck } from "@/lib/api/firecrawl";

// Re-export the type and utility for convenience
export type ScrapedData = ScrapedProjectData;
export const isUrl = isUrlCheck;

// Extract domain name from URL for project name
const extractDomainName = (url: string): string => {
  try {
    let cleanUrl = url.trim();
    if (cleanUrl.startsWith('www.')) {
      cleanUrl = 'https://' + cleanUrl;
    }
    const urlObj = new URL(cleanUrl);
    const hostname = urlObj.hostname.replace(/^www\./, '');
    // Get first part of domain
    const parts = hostname.split('.');
    return parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
  } catch {
    return 'Scraped Project';
  }
};

// Mock data variations based on URL patterns
const getMockDataForUrl = (url: string): ScrapedData => {
  const lowerUrl = url.toLowerCase();
  
  if (lowerUrl.includes('eco') || lowerUrl.includes('green') || lowerUrl.includes('sustainable')) {
    return {
      name: extractDomainName(url) + ' - Sustainability Platform',
      problem: 'Businesses struggle to track and reduce their carbon footprint effectively',
      solution: 'AI-powered sustainability dashboard that automates carbon tracking and suggests actionable reduction strategies',
      audience: 'investors',
    };
  }
  
  if (lowerUrl.includes('health') || lowerUrl.includes('med') || lowerUrl.includes('care')) {
    return {
      name: extractDomainName(url) + ' Health',
      problem: 'Patients face long wait times and fragmented healthcare communication',
      solution: 'Unified patient portal with AI triage, appointment scheduling, and real-time provider messaging',
      audience: 'judges',
    };
  }
  
  if (lowerUrl.includes('ai') || lowerUrl.includes('ml') || lowerUrl.includes('auto')) {
    return {
      name: extractDomainName(url) + ' AI',
      problem: 'Manual data entry consumes 40% of knowledge workers\' time',
      solution: 'Intelligent automation platform that learns from user behavior to auto-complete repetitive tasks',
      audience: 'judges',
    };
  }
  
  if (lowerUrl.includes('edu') || lowerUrl.includes('learn') || lowerUrl.includes('study')) {
    return {
      name: extractDomainName(url) + ' Learning',
      problem: 'Traditional education fails to adapt to individual learning speeds and styles',
      solution: 'Adaptive learning platform using spaced repetition and personalized content paths',
      audience: 'academic',
    };
  }
  
  // Default mock data
  return {
    name: extractDomainName(url),
    problem: 'Existing solutions are slow, expensive, and difficult to use',
    solution: 'A streamlined platform that automates the workflow with AI-powered insights',
    audience: 'judges',
  };
};

/**
 * Simulates scraping a URL and returning extracted data
 * @param url - The URL to "scrape"
 * @returns Promise that resolves with scraped data after a delay
 */
export const mockScrapeUrl = async (url: string): Promise<ScrapedData> => {
  // Simulate network delay (2-4 seconds)
  const delay = 2000 + Math.random() * 2000;
  await new Promise(resolve => setTimeout(resolve, delay));
  
  return getMockDataForUrl(url);
};

// Constants for script generation
const WORDS_PER_MINUTE = 150;

// Generate content based on word count target
const generateScaledContent = (baseContent: string, targetWords: number): string => {
  const currentWords = baseContent.split(/\s+/).length;
  if (currentWords >= targetWords) return baseContent;
  
  // Add more detail to reach target
  const expansionFactor = Math.min(3, targetWords / currentWords);
  if (expansionFactor > 1.5) {
    return `${baseContent}. We've validated this approach through extensive user research and competitive analysis. Our unique positioning in the market gives us a significant first-mover advantage.`;
  }
  return baseContent;
};

/**
 * Generate a mock script based on scraped or input data
 * Now accepts durationMinutes to scale the generated content appropriately
 */
export interface AutoGeneratedPitch {
  idea: string;
  track: 'hackathon-no-demo' | 'investor';
  audienceLabel: string;
  durationMinutes: number;
  estimatedWords: number;
  trackData: {
    pain?: string;
    fix?: string;
    progress?: string;
    feasibility?: string;
    opportunity?: string;
    market?: string;
    traction?: string;
    businessModel?: string;
    ask?: string;
    // Additional fields for longer pitches
    team?: string;
    competition?: string;
    roadmap?: string;
    vision?: string;
  };
}

export const generateAutoPitch = (
  input: string, 
  scrapedData?: ScrapedData, 
  durationMinutes: number = 3
): AutoGeneratedPitch => {
  // Calculate target word count based on duration
  const targetWords = Math.round(durationMinutes * WORDS_PER_MINUTE);
  
  // Randomly select track if not determined by scraped data
  const isInvestor = scrapedData?.audience === 'investors' || Math.random() > 0.5;
  
  // For short pitches (< 1 min), keep content minimal
  const isShortPitch = durationMinutes < 1;
  // For long pitches (> 5 min), add additional sections
  const isLongPitch = durationMinutes >= 5;
  
  if (isInvestor) {
    const baseOpportunity = scrapedData?.problem || `The ${input} market is growing rapidly but lacks modern solutions`;
    const baseMarket = 'Global TAM of $50B with 15% CAGR, targeting SMB segment initially';
    const baseTraction = 'Currently in beta with 500+ waitlist signups and 3 pilot customers';
    const baseBusinessModel = 'SaaS subscription model with tiered pricing based on usage';
    const baseAsk = 'Seeking $500K seed round to expand engineering team and launch V1';
    
    const trackData: AutoGeneratedPitch['trackData'] = {
      opportunity: isShortPitch 
        ? `${input} market needs modern solutions` 
        : generateScaledContent(baseOpportunity, targetWords / 5),
      market: isShortPitch 
        ? '$50B TAM, 15% CAGR' 
        : generateScaledContent(baseMarket, targetWords / 5),
      traction: isShortPitch 
        ? '500+ waitlist, 3 pilots' 
        : generateScaledContent(baseTraction, targetWords / 5),
      businessModel: isShortPitch 
        ? 'SaaS subscription' 
        : generateScaledContent(baseBusinessModel, targetWords / 5),
      ask: isShortPitch 
        ? '$500K seed' 
        : generateScaledContent(baseAsk, targetWords / 5),
    };
    
    // Add extended sections for longer pitches
    if (isLongPitch) {
      trackData.team = 'Our founding team brings 30+ years combined experience from Google, Meta, and successful exits. We\'ve built and scaled products used by millions.';
      trackData.competition = 'While incumbents focus on enterprise, we\'re capturing the underserved mid-market. Our AI-first approach gives us 10x faster iteration cycles.';
      trackData.roadmap = 'Q1: Launch V1 with core features. Q2: Enterprise tier and API. Q3: International expansion. Q4: Series A raise targeting $5M.';
      trackData.vision = 'We envision a world where every business has access to enterprise-grade tools. By 2027, we aim to power 100,000+ companies globally.';
    }
    
    return {
      idea: scrapedData?.name || input,
      track: 'investor',
      audienceLabel: 'Investors',
      durationMinutes,
      estimatedWords: targetWords,
      trackData,
    };
  }
  
  // Hackathon track
  const basePain = scrapedData?.problem || `Users waste hours on manual processes that should be automated`;
  const baseFix = scrapedData?.solution || `AI-powered solution that reduces time by 80%`;
  const baseProgress = 'Built core functionality in 48 hours, integrated with 3 APIs';
  const baseFeasibility = 'Using proven tech stack: React, Node.js, and GPT-4 API';
  
  const trackData: AutoGeneratedPitch['trackData'] = {
    pain: isShortPitch 
      ? 'Manual processes waste hours daily' 
      : generateScaledContent(basePain, targetWords / 4),
    fix: isShortPitch 
      ? 'AI automation reduces time 80%' 
      : generateScaledContent(baseFix, targetWords / 4),
    progress: isShortPitch 
      ? 'Core MVP built in 48 hours' 
      : generateScaledContent(baseProgress, targetWords / 4),
    feasibility: isShortPitch 
      ? 'React + Node.js + GPT-4' 
      : generateScaledContent(baseFeasibility, targetWords / 4),
  };
  
  // Add extended sections for longer pitches
  if (isLongPitch) {
    trackData.team = 'Our team includes a former Google engineer, a UX designer from Figma, and a domain expert with 10 years in the industry.';
    trackData.vision = 'Post-hackathon, we plan to launch a beta, gather user feedback, and pursue Y Combinator. Our goal is to make this the default solution for the industry.';
    trackData.roadmap = 'Next steps: polish the demo, add user authentication, implement analytics, and prepare for a ProductHunt launch.';
  }
  
  return {
    idea: scrapedData?.name || input,
    track: 'hackathon-no-demo',
    audienceLabel: 'Hackathon Judges',
    durationMinutes,
    estimatedWords: targetWords,
    trackData,
  };
};
