/**
 * Mock URL Scraper Service
 * Simulates scraping a website to extract project information
 */

export interface ScrapedData {
  name: string;
  problem: string;
  solution: string;
  audience: string;
}

// Regex to detect URLs
export const isUrl = (input: string): boolean => {
  const urlPattern = /^(https?:\/\/|www\.)/i;
  return urlPattern.test(input.trim());
};

// Extract domain name from URL for project name
const extractDomainName = (url: string): string => {
  try {
    let cleanUrl = url.trim();
    if (cleanUrl.startsWith('www.')) {
      cleanUrl = 'https://' + cleanUrl;
    }
    const urlObj = new URL(cleanUrl);
    const hostname = urlObj.hostname.replace(/^www\./, '');
    // Get first part of domain
    const parts = hostname.split('.');
    return parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
  } catch {
    return 'Scraped Project';
  }
};

// Mock data variations based on URL patterns
const getMockDataForUrl = (url: string): ScrapedData => {
  const lowerUrl = url.toLowerCase();
  
  if (lowerUrl.includes('eco') || lowerUrl.includes('green') || lowerUrl.includes('sustainable')) {
    return {
      name: extractDomainName(url) + ' - Sustainability Platform',
      problem: 'Businesses struggle to track and reduce their carbon footprint effectively',
      solution: 'AI-powered sustainability dashboard that automates carbon tracking and suggests actionable reduction strategies',
      audience: 'investors',
    };
  }
  
  if (lowerUrl.includes('health') || lowerUrl.includes('med') || lowerUrl.includes('care')) {
    return {
      name: extractDomainName(url) + ' Health',
      problem: 'Patients face long wait times and fragmented healthcare communication',
      solution: 'Unified patient portal with AI triage, appointment scheduling, and real-time provider messaging',
      audience: 'judges',
    };
  }
  
  if (lowerUrl.includes('ai') || lowerUrl.includes('ml') || lowerUrl.includes('auto')) {
    return {
      name: extractDomainName(url) + ' AI',
      problem: 'Manual data entry consumes 40% of knowledge workers\' time',
      solution: 'Intelligent automation platform that learns from user behavior to auto-complete repetitive tasks',
      audience: 'judges',
    };
  }
  
  if (lowerUrl.includes('edu') || lowerUrl.includes('learn') || lowerUrl.includes('study')) {
    return {
      name: extractDomainName(url) + ' Learning',
      problem: 'Traditional education fails to adapt to individual learning speeds and styles',
      solution: 'Adaptive learning platform using spaced repetition and personalized content paths',
      audience: 'academic',
    };
  }
  
  // Default mock data
  return {
    name: extractDomainName(url),
    problem: 'Existing solutions are slow, expensive, and difficult to use',
    solution: 'A streamlined platform that automates the workflow with AI-powered insights',
    audience: 'judges',
  };
};

/**
 * Simulates scraping a URL and returning extracted data
 * @param url - The URL to "scrape"
 * @returns Promise that resolves with scraped data after a delay
 */
export const mockScrapeUrl = async (url: string): Promise<ScrapedData> => {
  // Simulate network delay (2-4 seconds)
  const delay = 2000 + Math.random() * 2000;
  await new Promise(resolve => setTimeout(resolve, delay));
  
  return getMockDataForUrl(url);
};

/**
 * Generate a mock script based on scraped or input data
 */
export interface AutoGeneratedPitch {
  idea: string;
  track: 'hackathon-no-demo' | 'investor';
  audienceLabel: string;
  trackData: {
    pain?: string;
    fix?: string;
    progress?: string;
    feasibility?: string;
    opportunity?: string;
    market?: string;
    traction?: string;
    businessModel?: string;
    ask?: string;
  };
}

export const generateAutoPitch = (input: string, scrapedData?: ScrapedData): AutoGeneratedPitch => {
  // Randomly select track if not determined by scraped data
  const isInvestor = scrapedData?.audience === 'investors' || Math.random() > 0.5;
  
  if (isInvestor) {
    return {
      idea: scrapedData?.name || input,
      track: 'investor',
      audienceLabel: 'Investors',
      trackData: {
        opportunity: scrapedData?.problem || `The ${input} market is growing rapidly but lacks modern solutions`,
        market: 'Global TAM of $50B with 15% CAGR, targeting SMB segment initially',
        traction: 'Currently in beta with 500+ waitlist signups and 3 pilot customers',
        businessModel: 'SaaS subscription model with tiered pricing based on usage',
        ask: 'Seeking $500K seed round to expand engineering team and launch V1',
      },
    };
  }
  
  return {
    idea: scrapedData?.name || input,
    track: 'hackathon-no-demo',
    audienceLabel: 'Hackathon Judges',
    trackData: {
      pain: scrapedData?.problem || `Users waste hours on manual processes that should be automated`,
      fix: scrapedData?.solution || `AI-powered solution that reduces time by 80%`,
      progress: 'Built core functionality in 48 hours, integrated with 3 APIs',
      feasibility: 'Using proven tech stack: React, Node.js, and GPT-4 API',
    },
  };
};
